/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fi.ville.piaqparser.ui;

import fi.ville.piaqparser.services.MittausAnalysoijaPalvelu;
import javax.swing.BoxLayout;
import javax.swing.JCheckBox;
import javax.swing.JRadioButton;

/**
 *
 * @author ville
 */
public class UusiUI extends javax.swing.JPanel implements AsetaTekstiRajapinta{

    /**
     * Creates new form UusiUI
     */
    public UusiUI() {
        initComponents();
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dataForEveryButtonGroup = new javax.swing.ButtonGroup();
        CommandsWindow = new javax.swing.JPanel();
        Commands = new javax.swing.JLabel();
        makeNewXML = new javax.swing.JButton();
        TimeWindow = new javax.swing.JPanel();
        TimeLabel = new javax.swing.JLabel();
        thisSheetHasDataFrom = new javax.swing.JLabel();
        DataFrom = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DataTo = new javax.swing.JLabel();
        UseDataFrom = new javax.swing.JLabel();
        ParametersWindow = new javax.swing.JPanel();
        Parameters = new javax.swing.JLabel();
        values = new javax.swing.JLabel();
        dataForEvery = new javax.swing.JLabel();
        radioButton1second = new javax.swing.JRadioButton();
        radioButton15seconds = new javax.swing.JRadioButton();
        radioButton30seconds = new javax.swing.JRadioButton();
        radioButton1minute = new javax.swing.JRadioButton();
        radioButton5minutes = new javax.swing.JRadioButton();
        radioButton15minutes = new javax.swing.JRadioButton();
        radioButton1hour = new javax.swing.JRadioButton();
        valuesButtonsPanel = new javax.swing.JPanel();

        CommandsWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Commands.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Commands.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Commands.setText("Commands");

        makeNewXML.setText("Make a new Excel(XML)");

        javax.swing.GroupLayout CommandsWindowLayout = new javax.swing.GroupLayout(CommandsWindow);
        CommandsWindow.setLayout(CommandsWindowLayout);
        CommandsWindowLayout.setHorizontalGroup(
            CommandsWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandsWindowLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(makeNewXML)
                .addContainerGap(407, Short.MAX_VALUE))
            .addComponent(Commands, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        CommandsWindowLayout.setVerticalGroup(
            CommandsWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CommandsWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Commands, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(makeNewXML)
                .addGap(23, 23, 23))
        );

        TimeWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        TimeLabel.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        TimeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TimeLabel.setText("Time");

        thisSheetHasDataFrom.setText("This sheet has data from");

        DataFrom.setText("jLabel1");

        jLabel2.setText("To");

        DataTo.setText("jLabel1");

        UseDataFrom.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        UseDataFrom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        UseDataFrom.setText("Use data from");

        javax.swing.GroupLayout TimeWindowLayout = new javax.swing.GroupLayout(TimeWindow);
        TimeWindow.setLayout(TimeWindowLayout);
        TimeWindowLayout.setHorizontalGroup(
            TimeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TimeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(UseDataFrom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(TimeWindowLayout.createSequentialGroup()
                .addGroup(TimeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TimeWindowLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(thisSheetHasDataFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimeWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DataTo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TimeWindowLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(DataFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        TimeWindowLayout.setVerticalGroup(
            TimeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TimeWindowLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(thisSheetHasDataFrom)
                .addGap(18, 18, 18)
                .addGroup(TimeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DataFrom)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DataTo)
                .addGap(18, 18, 18)
                .addComponent(UseDataFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        ParametersWindow.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Parameters.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        Parameters.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Parameters.setText("Parameters");

        values.setText("Values");

        dataForEvery.setText("Data for every");

        dataForEveryButtonGroup.add(radioButton1second);
        radioButton1second.setText("1 second");

        dataForEveryButtonGroup.add(radioButton15seconds);
        radioButton15seconds.setText("15 seconds");

        dataForEveryButtonGroup.add(radioButton30seconds);
        radioButton30seconds.setText("30 seconds");

        dataForEveryButtonGroup.add(radioButton1minute);
        radioButton1minute.setText("1 minute");

        dataForEveryButtonGroup.add(radioButton5minutes);
        radioButton5minutes.setText("5 minutes");

        dataForEveryButtonGroup.add(radioButton15minutes);
        radioButton15minutes.setText("15 minutes");

        dataForEveryButtonGroup.add(radioButton1hour);
        radioButton1hour.setText("1 hour");

        javax.swing.GroupLayout valuesButtonsPanelLayout = new javax.swing.GroupLayout(valuesButtonsPanel);
        valuesButtonsPanel.setLayout(valuesButtonsPanelLayout);
        valuesButtonsPanelLayout.setHorizontalGroup(
            valuesButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        valuesButtonsPanelLayout.setVerticalGroup(
            valuesButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout ParametersWindowLayout = new javax.swing.GroupLayout(ParametersWindow);
        ParametersWindow.setLayout(ParametersWindowLayout);
        ParametersWindowLayout.setHorizontalGroup(
            ParametersWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Parameters, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ParametersWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ParametersWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(values, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(valuesButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(ParametersWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataForEvery, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                    .addComponent(radioButton1hour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButton15minutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButton5minutes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButton1minute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButton30seconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButton15seconds, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radioButton1second, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ParametersWindowLayout.setVerticalGroup(
            ParametersWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParametersWindowLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(Parameters, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(ParametersWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(values)
                    .addComponent(dataForEvery))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ParametersWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ParametersWindowLayout.createSequentialGroup()
                        .addComponent(radioButton1second)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton15seconds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton30seconds)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton1minute)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton5minutes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton15minutes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radioButton1hour))
                    .addComponent(valuesButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CommandsWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TimeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ParametersWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TimeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ParametersWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CommandsWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Commands;
    private javax.swing.JPanel CommandsWindow;
    private javax.swing.JLabel DataFrom;
    private javax.swing.JLabel DataTo;
    private javax.swing.JLabel Parameters;
    private javax.swing.JPanel ParametersWindow;
    private javax.swing.JLabel TimeLabel;
    private javax.swing.JPanel TimeWindow;
    private javax.swing.JLabel UseDataFrom;
    private javax.swing.JLabel dataForEvery;
    private javax.swing.ButtonGroup dataForEveryButtonGroup;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton makeNewXML;
    private javax.swing.JRadioButton radioButton15minutes;
    private javax.swing.JRadioButton radioButton15seconds;
    private javax.swing.JRadioButton radioButton1hour;
    private javax.swing.JRadioButton radioButton1minute;
    private javax.swing.JRadioButton radioButton1second;
    private javax.swing.JRadioButton radioButton30seconds;
    private javax.swing.JRadioButton radioButton5minutes;
    private javax.swing.JLabel thisSheetHasDataFrom;
    private javax.swing.JLabel values;
    private javax.swing.JPanel valuesButtonsPanel;
    // End of variables declaration//GEN-END:variables

    
    @Override
    public void addCheckBoxToValuesButtonGroup(JCheckBox box){
        valuesButtonsPanel.setLayout(new BoxLayout(valuesButtonsPanel, BoxLayout.Y_AXIS));
        
        valuesButtonsPanel.add(box);
    }
    
    
    
    @Override
    public String getDateFrom() {
        return DataFrom.getText();
    }

    @Override
    public void setDateFrom(String teksti) {
        DataFrom.setText(teksti);
    }
    
    @Override
    public String getDateTo(){
        return DataTo.getText();
    }
    
    @Override
    public void setDateTo(String teksti){
        DataTo.setText(teksti);
    }
}
